"""Derived artifacts regenerated from the index — never hand-edited.

``llms.txt`` (Company-Brain Prompt 7) is the door an AI walks through to read
the brain: a per-folder list of ``- [[note]] -- summary`` taken straight from
frontmatter. ``_showcase/showcase.md`` (Prompt 8) is the photograph for a
demo: how many notes, how many links, how many connected components, a
notes-per-folder table, and the hub summaries.

Both are *derived*: the generator below rebuilds them from scratch every time
off the index, so they can never drift from the notes. A header banner marks
them as machine-written so a human (or the agent) knows not to edit them.
"""
from __future__ import annotations

from src.memory.vault import taxonomy
from src.memory.vault.index import VaultIndex

_LLMS_BANNER = (
    "<!-- AUTO-GENERATED by OpenAgent vault. Do not edit by hand — it is "
    "regenerated from note frontmatter. -->"
)


def _content_notes(index: VaultIndex):
    """All gateable notes (skip raw material + excluded folders), grouped by
    folder in a stable order: the canonical content folders first, then any
    other folders present, then root notes."""
    from src.memory.vault.model import _DEFAULT_EXCLUDED
    notes = [
        n for n in index.all_notes()
        if not taxonomy.is_excluded(n.path, _DEFAULT_EXCLUDED)
        and not taxonomy.is_raw(n.path)
    ]
    by_folder: dict[str, list] = {}
    for n in notes:
        by_folder.setdefault(n.folder, []).append(n)
    ordered_folders: list[str] = []
    for f in taxonomy.CONTENT_FOLDERS:
        if f in by_folder:
            ordered_folders.append(f)
    for f in sorted(by_folder):
        if f not in ordered_folders and f != "":
            ordered_folders.append(f)
    if "" in by_folder:
        ordered_folders.append("")
    return by_folder, ordered_folders


def generate_llms_txt(index: VaultIndex) -> str:
    by_folder, ordered = _content_notes(index)
    lines = [_LLMS_BANNER, "", "# Vault index (llms.txt)", ""]
    for folder in ordered:
        header = folder if folder else "(root)"
        lines.append(f"## {header}")
        for n in sorted(by_folder[folder], key=lambda x: x.stem.lower()):
            summary = (n.summary or "").strip().replace("\n", " ")
            link = n.path[:-3] if n.path.lower().endswith(".md") else n.path
            if summary:
                lines.append(f"- [[{link}]] -- {summary}")
            else:
                lines.append(f"- [[{link}]]")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def generate_showcase(index: VaultIndex) -> str:
    stats = index.stats()
    by_folder, ordered = _content_notes(index)

    lines = [
        _LLMS_BANNER,
        "",
        "# Vault showcase",
        "",
        f"- **Notes**: {stats['notes']}",
        f"- **Wikilinks**: {stats['links']}  "
        f"(broken: {stats['broken_links']})",
        f"- **Connected components**: {stats['components']} "
        f"(1 = fully connected; largest has {stats['largest_component']} notes)",
        f"- **Orphans**: {stats['orphans']}",
        "",
        "## Notes per folder",
        "",
        "| Folder | Notes |",
        "| --- | --- |",
    ]
    for folder in ordered:
        header = folder if folder else "(root)"
        lines.append(f"| {header} | {len(by_folder[folder])} |")

    # Hub summaries: the _index of each folder, if present.
    hub_lines: list[str] = []
    for folder in ordered:
        for n in by_folder[folder]:
            if n.is_index and (n.summary or "").strip():
                hub_lines.append(f"- **{folder or '(root)'}** — {n.summary.strip()}")
                break
    if hub_lines:
        lines += ["", "## Hubs", ""] + hub_lines

    return "\n".join(lines).rstrip() + "\n"
