"""Trusted, turn-scoped execution-host context.

Client-machine capabilities are deliberately *not* session state.  A session
can be resumed from another device and server-owned work (schedules, events,
workflows and bridges) has no client seat at all.  The gateway therefore binds
an origin to the task that executes one interactive turn.  ``ContextVar``
propagation lets synchronous delegated children inherit that origin while the
automation entry points explicitly clear it.

Nothing in an inbound model/user payload can construct this value: the gateway
derives ``device_id`` from the verified device certificate and resolves the
exact capability connection before installing it.
"""

from __future__ import annotations

import asyncio
from contextlib import contextmanager
from contextvars import Context, ContextVar, Token, copy_context
from dataclasses import dataclass, field
from typing import Any, Coroutine, Iterator


@dataclass(frozen=True, slots=True)
class TurnExecutionOrigin:
    """The exact client capability host attached to one interactive turn."""

    device_id: str
    client_instance_id: str
    generation: int
    device_label: str
    # Registry is intentionally not serialised or shown in repr.  Keeping the
    # resolved dispatcher on the trusted value avoids a process-global routing
    # singleton and makes tests/multiple Gateway instances isolation-safe.
    registry: Any = field(repr=False, compare=False)
    # Private transport-authorization incarnation. Reconnects inside the same
    # epoch may resume safe calls; a post-suspension/revocation connection may
    # not inherit work from the older turn even if instance/generation match.
    auth_epoch: int = field(default=0, repr=False)

    @property
    def execution_host(self) -> dict[str, Any]:
        return {
            "kind": "client",
            "device_id": self.device_id,
            "device_label": self.device_label,
            "client_instance_id": self.client_instance_id,
            "generation": self.generation,
        }


@dataclass(frozen=True, slots=True)
class TrustedTurnContext:
    """Immutable authorization and rendering policy for one client ingress.

    The Gateway snapshots this from the authenticated connection.  It is kept
    next to (but separate from) capability routing so a turn with no local MCP
    host still retains its exact principal and client feature set.  Tuples make
    the capability map immutable while it crosses debounce/STT queues.
    """

    on_behalf_identity: Any = field(repr=False, compare=False)
    client_kind: str | None = None
    client_capabilities: tuple[tuple[str, bool | int | str], ...] = ()
    allow_local_attachment_paths: bool = False

    def supports_client_capability(self, name: str, *, version: int = 1) -> bool:
        value = dict(self.client_capabilities).get(name)
        if isinstance(value, bool):
            return value
        if isinstance(value, int):
            return value >= version
        return False


@dataclass(frozen=True, slots=True)
class TrustedIngressIdentity:
    """Authenticated chat transport that supplied one inbound event.

    This identity exists even when the device has not enabled local tools.
    ``connection_id`` is generated by the Gateway, so a client cannot forge or
    select another ingress owner.  It is intentionally separate from
    :class:`TurnExecutionOrigin`: the latter is optional capability routing,
    while this value always prevents cross-device burst/audio/media mixing.
    """

    device_id: str
    connection_id: str
    client_instance_id: str | None = None
    # Private authorization epoch captured by middleware. It is never decoded
    # from the event wire and lets a delayed revocation callback distinguish an
    # old socket from a freshly authenticated post-reactivation socket.
    auth_epoch: int = 0
    # Present only when the Gateway captured the connection's authenticated
    # turn policy. ``None`` preserves the direct/legacy StreamSession API,
    # whose constructor-level values remain the fallback for local callers.
    turn_context: TrustedTurnContext | None = field(
        default=None, repr=False, compare=False,
    )


_origin_var: ContextVar[TurnExecutionOrigin | None] = ContextVar(
    "openagent_turn_execution_origin", default=None,
)


def current_execution_origin() -> TurnExecutionOrigin | None:
    """Return the current trusted origin, or ``None`` for server-only work."""

    return _origin_var.get()


def install_execution_origin(
    origin: TurnExecutionOrigin | None,
) -> Token[TurnExecutionOrigin | None]:
    """Install ``origin`` for the current task and return a reset token."""

    return _origin_var.set(origin)


def reset_execution_origin(token: Token[TurnExecutionOrigin | None]) -> None:
    _origin_var.reset(token)


def server_only_task_context() -> Context:
    """Copy the current context with client capability routing cleared.

    ``asyncio.create_task`` normally inherits ContextVars. That is correct for
    synchronous delegated children of an interactive turn, but wrong for
    detached/durable work such as compaction, scoring, hooks and webhooks: it
    may outlive the turn and must never retain access to the user's machine.
    """

    context = copy_context()
    context.run(_origin_var.set, None)
    return context


def create_server_only_task(
    coroutine: Coroutine[Any, Any, Any],
    *,
    name: str | None = None,
) -> asyncio.Task[Any]:
    """Schedule detached work in an explicit server-only execution context."""

    return asyncio.get_running_loop().create_task(
        coroutine,
        name=name,
        context=server_only_task_context(),
    )


@contextmanager
def execution_origin_scope(
    origin: TurnExecutionOrigin | None,
) -> Iterator[None]:
    """Temporarily bind an origin; passing ``None`` is an explicit clear."""

    token = install_execution_origin(origin)
    try:
        yield
    finally:
        reset_execution_origin(token)
