// AUTO-GENERATED by src/memory/vault/taxonomy.py -- DO NOT EDIT BY HAND.
//
// Regenerate:  .venv/bin/python -m src.memory.vault.taxonomy
// Pinned by:   scripts/tests/test_vault_twins.py (CI fails on drift)
//
// WHY THIS FILE EXISTS: "which notes does the quality system apply to?" is a
// vault-taxonomy question, and the taxonomy is declared in Python. This file
// is the derived copy the Node writer reads, because it runs as a separate
// process in another language and cannot call the declaration directly. It is
// generated rather than hand-kept: the hand-kept version drifted, and 413
// notes (20% of the owner's real vault) were skipped by this writer while the
// Python gate graded and failed them.

export const EXCLUDED_FOLDERS: readonly string[] = ["sources", "_showcase", "_templates", "templates", ".obsidian", ".git", ".openagent"];
export const RAW_PREFIXES: readonly string[] = ["sources/", "workspace/"];
export const JOURNAL_ROOT = "workspace/journal";

const norm = (p: string): string => p.replace(/\\/g, "/").replace(/^\/+/, "");

/** Port of taxonomy.is_journal_note. */
export function isJournalNote(relPath: string): boolean {
  const p = norm(relPath);
  const root = JOURNAL_ROOT.replace(/\\/g, "/").replace(/^\/+|\/+$/g, "");
  return p === root || p.startsWith(root + "/");
}

/** Port of taxonomy.is_excluded. A dot-directory is excluded by rule, not by
 *  name: an enumeration of tooling folders goes stale (it had already missed
 *  Obsidian's .trash/). */
export function isExcluded(relPath: string): boolean {
  const parts = norm(relPath).split("/");
  const parents = parts.slice(0, -1);
  if (parents.some((s) => s.startsWith("."))) return true;
  return (
    parents.some((s) => EXCLUDED_FOLDERS.includes(s)) ||
    EXCLUDED_FOLDERS.includes(parts[0] ?? "")
  );
}

/** Port of taxonomy.is_raw. The journal is carved back in: it is dynamic
 *  memory, not scratch. */
export function isRaw(relPath: string): boolean {
  const p = norm(relPath);
  if (isJournalNote(p)) return false;
  return RAW_PREFIXES.some((prefix) => p.startsWith(prefix));
}

/** Port of taxonomy.is_in_quality_scope. */
export function isInQualityScope(relPath: string): boolean {
  return !isExcluded(relPath) && !isRaw(relPath);
}
